### ISSUE TITLE
[Question] Where are TTS and ASR from

### ISSUE THREAD

**Issue by smolendawid** [blamarche/VoiceGoban#1]
I don't get where are Text to speech and Speech recognition engines from. Are they built in in the system? Or does it require internet connection? Or maybe the audio is prerecorded?

**Comment by blamarche** [comment]
Hi there. The engine is built into windows and do not (as far as I know) send recording data to Microsoft. The voices are synthesized locally and VoiceGoban should not require internet access. You can read up on it here: https://en.wikipedia.org/wiki/Microsoft_Speech_API
